AWSTemplateFormatVersion: 2010-09-09
Description: |
  hello
Resources:
  mySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SHH and Http # Required
      GroupName: osvaldoportfolio
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: mesut
​  myWebServer:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-01c647eace872fc02
    InstanceType: t2.micro
    KeyName: firstkey
    SecurityGroupIds:
      - !Ref mySecGrp
    Tags:
      - Key: Name
        Value:
    UserData:
      Fn::Base64: |
        #! /bin/bash
        yum update -y
        yum install httpd -y
        FOLDER="https://raw.githubusercontent.com/MeesS30/101-kittens-carousel-static-website/main/static-web"
        cd /var/www/html
        wget ${FOLDER}/index.html
        wget ${FOLDER}/cat0.jpg
        wget ${FOLDER}/cat1.jpg
        wget ${FOLDER}/cat2.jpg
        wget ${FOLDER}/cat3.png
        systemctl start httpd
        systemctl enable httpd
Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt myWebServer.PublicDnsName
    Description: Kittens Carousel Application URL
